set nocompatible              " Required to be iMproved
filetype off                  " Required

" Automatic installation of vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Color scheme
Plug 'nanotech/jellybeans.vim'

" Plugins
Plug 'junegunn/fzf', {'do': {->fzf#install()}}
Plug 'junegunn/fzf.vim'

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'maxmellon/vim-jsx-pretty'

" Initialize plugin system
call plug#end()

colorscheme jellybeans

syntax enable
highlight Normal  ctermbg=none
highlight NonText ctermbg=none
highlight LineNr  ctermbg=none

" Leader
map <Space> <Leader>

set autochdir
set encoding=utf-8  " Set encodign to utf-8 to browse through unicode
set backspace=2     " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile
set history=50
set ruler           " Show the cursor position all the time
set mouse=n         " Necessary to use mouse as cursor
set showcmd         " Display incomplete commands
set incsearch       " Do incremental searching
set laststatus=2    " Always display the status line
set autowrite       " Automatically :write before running commands
set guicursor=      " Fuck neovim change cursor style
set clipboard+=unnamedplus     " Use clipboard in neovim
set ignorecase            " Search will ignore all cases
set smartcase             " Type Uppercase to be case sensitive
set foldmethod=indent     " Set fold method to indent
set foldlevel=99          " Set default to unfold

" Numbers
set number relativenumber
set numberwidth=5

" Toggle hybrid line numbers
nnoremap <C-n> :set nu! rnu!<CR>

" Clipboard copy/paste
nnoremap <Leader>y "*y
nnoremap <Leader>p "*p
" Select all
nnoremap <C-a> ggVG

" Resovle conflict block select
nnoremap <C-q> <C-v>
" Map capitalized u as redo
nnoremap U :redo<CR>
" Clear highlight after search
nnoremap <CR> :noh<CR>

" Toggle netrw explorer 
nnoremap <C-e> :Lexplore<CR>
nnoremap <C-r> :Rexplore<CR>
let g:netrw_banner=0
let g:netrw_winsize=25
" Use fzf for searching
nnoremap <C-f> :Files<CR>

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set smarttab
set shiftround
set expandtab

" Fuck 4 spaces, 2 spaces is the way
let g:rust_recommended_style=0

" Turn 'paste' on and off
set pastetoggle=<F2>

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
