export VISUAL=vim
export EDITOR=$VISUAL

# Path to your oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# Install Ruby Gems to ~/gems
export GEM_HOME=$HOME/gems
export PATH=$HOME/gems/bin:$PATH

# Clone the nvm repository to ~/.nvm
# Add the source line to the profile
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Set name of the theme to load
ZSH_THEME="ys"

# Make color constants available
autoload -U colors
colors

# Enable colored output from ls, etc. on FreeBSD-based systems
export CLICOLOR=1

# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Prevent accidentally clobbering files
alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'

alias mkdir='mkdir -p'

alias h='history'
alias j='jobs -l'
alias which='type -a'
alias ..='cd ..'

# Make a more readable output
alias du='du -kh'
alias df='df -kTh'

# Add colors for filetype and human-readable sizes for default on 'ls'
alias ls='ls -h --color'
alias lx='ls -lXB'         #  Sort by extension
alias lk='ls -lSr'         #  Sort by size, biggest last
alias lt='ls -ltr'         #  Sort by date, most recent last
alias lc='ls -ltcr'        #  Sort by/show change time,most recent last
alias lu='ls -ltur'        #  Sort by/show access time,most recent last

# The ubiquitous 'll': directories first, with alphanumeric sorting
alias lm='ll |more'        #  Pipe through 'more'
alias lr='ll -R'           #  Recursive ls
alias la='ll -A'           #  Show hidden files
alias tree='tree -Csuh'    #  Nice alternative to 'recursive ls'
