# Add by zinit installer
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
# End of zinit installer

# Fast load plugin without track and report
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting

# Most themes require promptsubst
setopt promptsubst

# Source libs from oh my zsh repo
zinit snippet OMZL::git.zsh
zinit snippet OMZL::key-bindings.zsh
zinit snippet OMZL::completion.zsh
zinit snippet OMZL::compfix.zsh
# Load plugins from oh my zsh repo
zinit snippet OMZP::command-not-found

# Make color constants available
autoload -U colors
colors

# Load theme from oh my zsh repo
zinit snippet OMZT::ys

export VISUAL=vim
export EDITOR=$VISUAL

# Run tmux on startup zsh (no startx)
if [[ $DISPLAY ]]; then
  [[ $- != *i* ]] && return
  [[ -z "$TMUX" ]] && exec tmux
fi

# Clone the nvm repository to ~/.nvm
# Add the source line to the profile
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Add environment path for executables
export PATH="$HOME/bin:$PATH"     # For nvim clipboard in windows
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"

# Import fzf key binding and completion
if [ -d $HOME/.config/fzf/ ]; then
  source $HOME/.config/fzf/key-bindings.zsh
  source $HOME/.config/fzf/completion.zsh
else
  echo '[error] fzf folder not exists'
fi

# Replace alias modern tools
alias ls='exa --all --group-directories-first'
alias la='exa --long --all --header'
alias tree='exa -T -l -L=2 -h -I="node_modules"'

alias cat='bat'
alias vim='nvim'
alias ranger='. ranger'
alias lg='lazygit'

# Prevent accidentally clobbering files
alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'

alias mkdir='mkdir -p'

alias cls='clear'
alias h='history'
alias j='jobs -l'
alias which='type -a'
alias ..='cd ..'

# Make a more readable output
alias du='du -kh'
alias df='df -kTh'

# Compile C++ source file with C++17
alias g++='g++ -std=c++17 -O2 -Wall'
