if [ ! -f $HOME/.zinit/bin/zinit.zsh ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
fi

# Add by zinit installer
source $HOME/.zinit/bin/zinit.zsh
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
# End of zinit installer

# Fast load plugin without track and report
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting

# Most themes require promptsubst
setopt promptsubst

# Source libs from oh my zsh repo
zinit snippet OMZL::git.zsh
zinit snippet OMZL::key-bindings.zsh
zinit snippet OMZL::completion.zsh
zinit snippet OMZL::compfix.zsh
# Load plugins from oh my zsh repo
zinit snippet OMZP::command-not-found

# Make color constants available
autoload -U colors
colors

# Load theme from oh my zsh repo
zinit snippet OMZT::ys

export VISUAL=vim
export EDITOR=$VISUAL

# Run tmux on startup zsh (no startx)
if command -v pacman > /dev/null; then
  if [[ $DISPLAY ]]; then
    [[ $- != *i* ]] && return
    [[ -z "$TMUX" ]] && exec tmux
  fi
elif command -v apt > /dev/null; then
  [[ $- != *i* ]] && return
  [[ -z "$TMUX" ]] && exec tmux
fi

# Clone the nvm repository to ~/.nvm
# Add the source line to the profile
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Add environment path for executables
export PATH="$HOME/bin:$PATH"     # For nvim clipboard in windows
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"

local CONFIG="$HOME/.config"

# Import fzf key binding and completion
[ -f $CONFIG/fzf/key-bindings.zsh ] && \
  source $CONFIG/fzf/key-bindings.zsh
[ -f $CONFIG/fzf/completion.zsh ] && \
  source $CONFIG/fzf/completion.zsh

# Replace alias modern tools
if type exa > /dev/null 2>&1; then
  alias ls='exa --all --group-directories-first'
  alias la='exa --long --all --header'
  alias tree='exa -T -l -L=2 -h -I="node_modules"'
fi

type bat > /dev/null 2>&1 && alias cat='bat'
type nvim > /dev/null 2>&1 && alias vim='nvim'

alias ranger='. ranger'
alias lg='lazygit'

# Prevent accidentally clobbering files
alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'

alias mkdir='mkdir -p'

alias cls='clear'
alias h='history'
alias j='jobs -l'
alias which='type -a'
alias ..='cd ..'

# Make a more readable output
alias du='du -kh'
alias df='df -kTh'

# Compile C++ source file with C++17
alias g++='g++ -std=c++17 -O2 -Wall'
